services:
  app:
    build: .
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0
      --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:rw
    depends_on:
      - db
    networks:
      - backend
    env_file:
      - ./.env
  db:
    image: postgres:16-bullseye
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
volumes:
  db: {}

networks:
  backend:
    # Use a custom driver which takes special options
    driver: bridge
